### ISSUE TITLE
Maximum active stream limit exceeded when trying to create stream

### ISSUE THREAD

**Issue by lucianocallero** [tkowalcz/tjahzi#128]
I'm having this warning frequently. _Maximum active stream limit exceeded when trying to create stream_

I tried to increase limits but it does not take effect on this error
  limits_config:
    max_streams_per_user: 250000  
    max_global_streams_per_user: 25000
    max_query_series: 100000
    max_label_value_length: 4096

Is there any way to troubleshoot this error? To increase logs or something else?

**Comment by tkowalcz** [comment]
Hi @lucianocallero. This is an error on Loki side, correct? AFAIK it's related to reporting labels with high cardinality. You probably need to look at your labels and check what are their values. What are you sending? What is the Tjahzi configuration?

**Comment by lucianocallero** [comment]
Hi @tkowalcz. Yes its a Loki side error, but i tried to change almost all parameters and it does not change. 
 i guess that is not that "big", this is an example

{environment="qa_qa", log_level="INFO", message_reported="parameters stored", server="fk-api-tomcat-7999df66f9-7k7qm", service_name="API"}

Is there anyway to know from from Tjahzi to add more info on this error?

**Comment by tkowalcz** [comment]
I don't think that there is any option that would help you. Tjahzi by design does not log stuff (it's a design decision that I might have to revisit someday). In the end Tjahzi knows only about stuff that is happening in the jvm/process/pod it runs in. If you have many services that overwhelm Loki it's best to look at the label values it gets.
