### ISSUE TITLE
log4j2-appender not checking for success response from Loki

### ISSUE THREAD

**Issue by Retrospector** [tkowalcz/tjahzi#57]
Hi,
we were debugging the log transmission of tjahzi to Loki to find out why certain logs were not transmitted.
After a good while of digging, we found a network issue that caused larger batches of logs not to arrive at the Loki server. 
Smaller batches that got though always got acknowledged by Loki with a 204 NO CONTENT response. The larger ones lost in the depths of our network did not trigger this response.

Is tjahzi checking for this response to determine the successful transmission of a batch of logs?
If it is, does it log unsuccessful transmissions somewhere?

Sadly I cannot check this myself since I have absolutely no experience with Java itself.

Thank you for your work, now that it's working it'll save us a lot of headaches!

**Comment by tkowalcz** [comment]
Hi,

glad you found it useful. 

Tjahzi checks http response codes and if the code is not "204 NO CONTENT" (or there is other http/tcp error) it will do two things: 
1. Log it to std out (which is more of a debug thing as I assume in server environment stdout of a process goes to /dev/null)
1. increments an error counter. I was sure I have documented monitoring aspect but turns out I was wrong. 

If you are monitoring your application using something like Graphite or Prometheus you might be using Dropwizard library to expose that data. In such case this [test](https://github.com/tkowalcz/tjahzi/blob/master/log4j2-appender/src/test/java/pl/tkowalcz/tjahzi/log4j2/LokiAppenderMonitoringTest.java) shows how you can gather stats from Tjahzi and expose them to your monitoring system.

If you have no experience with Java then parts of my explanation might be nuclear. Please don't hesitate to ask questions here. I'll try to help.

**Comment by tkowalcz** [comment]
I have added section on monitoring: https://github.com/tkowalcz/tjahzi/wiki/Monitoring.

**Comment by Retrospector** [comment]
Hi Tomasz,

thank you very much for your insights. 
We will look into the Monitoring options for easier debugging of potential future issues.

Thanks a lot for adding the Wiki page for it.
